# .github/workflows/docker-build-push.yml
name: Build and Push to GCP Artifact Registry

on:
  push:
    branches:
      - master
      - feature/DP-326-Use-registry-to-manage-and-build-images
  # Optionally allow manual triggers
  workflow_dispatch:

env:
  PROJECT_ID: client-x-429512
  REGISTRY: us-central1-docker.pkg.dev
  REPOSITORY: client-x-registry
  IMAGE_NAME: superset

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/914691528539/locations/global/workloadIdentityPools/github-actions-pool
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Get short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Superset images
        run: |
          # Set registry prefix and tag
          REGISTRY_PREFIX="${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}"
          SUPERSET_TAG=$(date +%Y%m%d-%H%M%S)

          # Build the main Superset image
          docker build \
            --target dev \
            --cache-from apache/superset-cache:3.10-slim-bookworm \
            -t ${REGISTRY_PREFIX}/superset:${SUPERSET_TAG} \
            -t ${REGISTRY_PREFIX}/superset:latest \
            .

          # Tag worker and beat images from the main build
          docker tag ${REGISTRY_PREFIX}/superset:${SUPERSET_TAG} ${REGISTRY_PREFIX}/superset-worker:${SUPERSET_TAG}
          docker tag ${REGISTRY_PREFIX}/superset:${SUPERSET_TAG} ${REGISTRY_PREFIX}/superset-worker:latest
          docker tag ${REGISTRY_PREFIX}/superset:${SUPERSET_TAG} ${REGISTRY_PREFIX}/superset-worker-beat:${SUPERSET_TAG}
          docker tag ${REGISTRY_PREFIX}/superset:${SUPERSET_TAG} ${REGISTRY_PREFIX}/superset-worker-beat:latest

      - name: Push Superset images
        run: |
          # Set registry prefix and tag
          REGISTRY_PREFIX="${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}"
          SUPERSET_TAG=$(date +%Y%m%d-%H%M%S)

          # Push all Superset images
          docker push ${REGISTRY_PREFIX}/superset:${SUPERSET_TAG}
          docker push ${REGISTRY_PREFIX}/superset:latest
          docker push ${REGISTRY_PREFIX}/superset-worker:${SUPERSET_TAG}
          docker push ${REGISTRY_PREFIX}/superset-worker:latest
          docker push ${REGISTRY_PREFIX}/superset-worker-beat:${SUPERSET_TAG}
          docker push ${REGISTRY_PREFIX}/superset-worker-beat:latest
